repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: ["--fix", "."]
        pass_filenames: false
      - id: ruff-format
        args: ["."]
        pass_filenames: false
